// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *VSphereContentLibrary) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereContentLibraryItem) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereGuestOSCustomization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVappContainer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVappEntity) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVirtualDisk) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVirtualMachine) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVirtualMachineSnapshot) Hub() {}
