// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *VSphereDatastoreCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereDatastoreClusterVmAntiAffinityRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereFile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereNasDatastore) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereStorageDrsVmOverride) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVmfsDatastore) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VSphereVmStoragePolicy) Hub() {}
