// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereVirtualMachineClassInitParameters struct {

	// The percentage of the available CPU capacity which will be reserved.
	CPUReservation *float64 `json:"cpuReservation,omitempty" tf:"cpu_reservation,omitempty"`

	// The number of CPUs.
	// The number of CPUs.
	Cpus *float64 `json:"cpus,omitempty" tf:"cpus,omitempty"`

	// The amount of memory in MB.
	// The amount of memory (in MB).
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// The percentage of memory reservation.
	// The percentage of the available memory capacity which will be reserved.
	MemoryReservation *float64 `json:"memoryReservation,omitempty" tf:"memory_reservation,omitempty"`

	// The name for the class.
	// The name of the virtual machine class.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifiers of the vGPU devices for the class. If this is set memory reservation needs to be 100.
	// A comma-separated list of GPU devices.
	VgpuDevices []*string `json:"vgpuDevices,omitempty" tf:"vgpu_devices,omitempty"`
}

type VSphereVirtualMachineClassObservation struct {

	// The percentage of the available CPU capacity which will be reserved.
	CPUReservation *float64 `json:"cpuReservation,omitempty" tf:"cpu_reservation,omitempty"`

	// The number of CPUs.
	// The number of CPUs.
	Cpus *float64 `json:"cpus,omitempty" tf:"cpus,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The amount of memory in MB.
	// The amount of memory (in MB).
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// The percentage of memory reservation.
	// The percentage of the available memory capacity which will be reserved.
	MemoryReservation *float64 `json:"memoryReservation,omitempty" tf:"memory_reservation,omitempty"`

	// The name for the class.
	// The name of the virtual machine class.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifiers of the vGPU devices for the class. If this is set memory reservation needs to be 100.
	// A comma-separated list of GPU devices.
	VgpuDevices []*string `json:"vgpuDevices,omitempty" tf:"vgpu_devices,omitempty"`
}

type VSphereVirtualMachineClassParameters struct {

	// The percentage of the available CPU capacity which will be reserved.
	// +kubebuilder:validation:Optional
	CPUReservation *float64 `json:"cpuReservation,omitempty" tf:"cpu_reservation,omitempty"`

	// The number of CPUs.
	// The number of CPUs.
	// +kubebuilder:validation:Optional
	Cpus *float64 `json:"cpus,omitempty" tf:"cpus,omitempty"`

	// The amount of memory in MB.
	// The amount of memory (in MB).
	// +kubebuilder:validation:Optional
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// The percentage of memory reservation.
	// The percentage of the available memory capacity which will be reserved.
	// +kubebuilder:validation:Optional
	MemoryReservation *float64 `json:"memoryReservation,omitempty" tf:"memory_reservation,omitempty"`

	// The name for the class.
	// The name of the virtual machine class.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifiers of the vGPU devices for the class. If this is set memory reservation needs to be 100.
	// A comma-separated list of GPU devices.
	// +kubebuilder:validation:Optional
	VgpuDevices []*string `json:"vgpuDevices,omitempty" tf:"vgpu_devices,omitempty"`
}

// VSphereVirtualMachineClassSpec defines the desired state of VSphereVirtualMachineClass
type VSphereVirtualMachineClassSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereVirtualMachineClassParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VSphereVirtualMachineClassInitParameters `json:"initProvider,omitempty"`
}

// VSphereVirtualMachineClassStatus defines the observed state of VSphereVirtualMachineClass.
type VSphereVirtualMachineClassStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereVirtualMachineClassObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VSphereVirtualMachineClass is the Schema for the VSphereVirtualMachineClasss API. Provides a VMware vSphere virtual machine class resource..
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereVirtualMachineClass struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cpus) || (has(self.initProvider) && has(self.initProvider.cpus))",message="spec.forProvider.cpus is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.memory) || (has(self.initProvider) && has(self.initProvider.memory))",message="spec.forProvider.memory is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VSphereVirtualMachineClassSpec   `json:"spec"`
	Status VSphereVirtualMachineClassStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereVirtualMachineClassList contains a list of VSphereVirtualMachineClasss
type VSphereVirtualMachineClassList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereVirtualMachineClass `json:"items"`
}

// Repository type metadata.
var (
	VSphereVirtualMachineClass_Kind             = "VSphereVirtualMachineClass"
	VSphereVirtualMachineClass_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereVirtualMachineClass_Kind}.String()
	VSphereVirtualMachineClass_KindAPIVersion   = VSphereVirtualMachineClass_Kind + "." + CRDGroupVersion.String()
	VSphereVirtualMachineClass_GroupVersionKind = CRDGroupVersion.WithKind(VSphereVirtualMachineClass_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereVirtualMachineClass{}, &VSphereVirtualMachineClassList{})
}
