apiVersion: storage.terasky.labs/v1alpha1
kind: VSphereStorageDrsVmOverride
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/vspherestoragedrsvmoverride
  labels:
    testing.upbound.io/example-name: drs_vm_override
  name: drs-vm-override
spec:
  forProvider:
    datastoreClusterId: ${data.vsphere_datastore_cluster.datastore_cluster.id}
    sdrsEnabled: false
    virtualMachineId: ${vsphere_virtual_machine.vm.id}

---

apiVersion: virtualmachine.terasky.labs/v1alpha1
kind: VSphereVirtualMachine
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/vspherestoragedrsvmoverride
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    datastoreId: ${data.vsphere_datastore.member_datastore.id}
    disk:
    - label: disk0
      size: 20
    guestId: otherLinux64Guest
    memory: 1024
    name: terraform-test
    networkInterface:
    - networkId: ${data.vsphere_network.network.id}
    numCpus: 2
    resourcePoolId: ${data.vsphere_resource_pool.pool.id}
