apiVersion: storage.terasky.labs/v1alpha1
kind: VSphereFile
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/vspherefile
  labels:
    testing.upbound.io/example-name: ubuntu_vmdk_upload
  name: ubuntu-vmdk-upload
spec:
  forProvider:
    createDirectories: true
    datacenter: dc-01
    datastore: datastore-01
    destinationFile: /my/dst/path/custom_ubuntu.vmdk
    sourceFile: /my/src/path/custom_ubuntu.vmdk
