apiVersion: inventory.terasky.labs/v1alpha1
kind: VSphereFolder
metadata:
  annotations:
    meta.upbound.io/example-id: inventory/v1alpha1/vspherefolder
  labels:
    testing.upbound.io/example-name: folder
  name: folder
spec:
  forProvider:
    datacenterId: 'datacenter-94048'
    path: terraform-test-folder
    type: vm
