apiVersion: hostandclustermanagement.terasky.labs/v1alpha1
kind: VSphereComputeClusterVmAffinityRule
metadata:
  annotations:
    meta.upbound.io/example-id: hostandclustermanagement/v1alpha1/vspherecomputeclustervmaffinityrule
  labels:
    testing.upbound.io/example-name: vm_affinity_rule
  name: vm-affinity-rule
spec:
  forProvider:
    computeClusterId: ${data.vsphere_compute_cluster.cluster.id}
    name: vm-affinity-rule
    virtualMachineIds: '${[for k, v in vsphere_virtual_machine.vm : v.id]}'

---

apiVersion: virtualmachine.terasky.labs/v1alpha1
kind: VSphereVirtualMachine
metadata:
  annotations:
    meta.upbound.io/example-id: hostandclustermanagement/v1alpha1/vspherecomputeclustervmaffinityrule
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    count: 2
    datastoreId: ${data.vsphere_datastore.datastore.id}
    disk:
    - label: disk0
      size: 20
    guestId: otherLinux64Guest
    memory: 1024
    name: foo-${count.index}
    networkInterface:
    - networkId: ${data.vsphere_network.network.id}
    numCpus: 1
    resourcePoolId: ${data.vsphere_compute_cluster.cluster.resource_pool_id}
