// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereCustomAttributeInitParameters struct {

	// The object type that this attribute may be
	// applied to. If not set, the custom attribute may be applied to any object
	// type. For a full list, review the Managed Object Types. Forces a new resource if changed.
	// Object type for which the custom attribute is valid. If not specified, the attribute is valid for all managed object types.
	ManagedObjectType *string `json:"managedObjectType,omitempty" tf:"managed_object_type,omitempty"`

	// The name of the custom attribute.
	// The display name of the custom attribute.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type VSphereCustomAttributeObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The object type that this attribute may be
	// applied to. If not set, the custom attribute may be applied to any object
	// type. For a full list, review the Managed Object Types. Forces a new resource if changed.
	// Object type for which the custom attribute is valid. If not specified, the attribute is valid for all managed object types.
	ManagedObjectType *string `json:"managedObjectType,omitempty" tf:"managed_object_type,omitempty"`

	// The name of the custom attribute.
	// The display name of the custom attribute.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type VSphereCustomAttributeParameters struct {

	// The object type that this attribute may be
	// applied to. If not set, the custom attribute may be applied to any object
	// type. For a full list, review the Managed Object Types. Forces a new resource if changed.
	// Object type for which the custom attribute is valid. If not specified, the attribute is valid for all managed object types.
	// +kubebuilder:validation:Optional
	ManagedObjectType *string `json:"managedObjectType,omitempty" tf:"managed_object_type,omitempty"`

	// The name of the custom attribute.
	// The display name of the custom attribute.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// VSphereCustomAttributeSpec defines the desired state of VSphereCustomAttribute
type VSphereCustomAttributeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereCustomAttributeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VSphereCustomAttributeInitParameters `json:"initProvider,omitempty"`
}

// VSphereCustomAttributeStatus defines the observed state of VSphereCustomAttribute.
type VSphereCustomAttributeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereCustomAttributeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VSphereCustomAttribute is the Schema for the VSphereCustomAttributes API. Provides a VMware vSphere custom attribute resource. This can be used to manage custom attributes in vSphere.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereCustomAttribute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VSphereCustomAttributeSpec   `json:"spec"`
	Status VSphereCustomAttributeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereCustomAttributeList contains a list of VSphereCustomAttributes
type VSphereCustomAttributeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereCustomAttribute `json:"items"`
}

// Repository type metadata.
var (
	VSphereCustomAttribute_Kind             = "VSphereCustomAttribute"
	VSphereCustomAttribute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereCustomAttribute_Kind}.String()
	VSphereCustomAttribute_KindAPIVersion   = VSphereCustomAttribute_Kind + "." + CRDGroupVersion.String()
	VSphereCustomAttribute_GroupVersionKind = CRDGroupVersion.WithKind(VSphereCustomAttribute_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereCustomAttribute{}, &VSphereCustomAttributeList{})
}
