// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VSphereComputeClusterVmAntiAffinityRuleInitParameters struct {

	// The managed object reference
	// ID of the cluster to put the group in.  Forces a new
	// resource if changed.
	// The managed object ID of the cluster.
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster. Default: true.
	// Enable this rule in the cluster.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When this value is true, prevents any virtual
	// machine operations that may violate this rule. Default: false.
	// When true, prevents any virtual machine operations that may violate this rule.
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The name of the rule. This must be unique in the cluster.
	// The unique name of the virtual machine group in the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run
	// on hosts different from each other.
	// The UUIDs of the virtual machines to run on hosts different from each other.
	// +listType=set
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

type VSphereComputeClusterVmAntiAffinityRuleObservation struct {

	// The managed object reference
	// ID of the cluster to put the group in.  Forces a new
	// resource if changed.
	// The managed object ID of the cluster.
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster. Default: true.
	// Enable this rule in the cluster.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When this value is true, prevents any virtual
	// machine operations that may violate this rule. Default: false.
	// When true, prevents any virtual machine operations that may violate this rule.
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The name of the rule. This must be unique in the cluster.
	// The unique name of the virtual machine group in the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run
	// on hosts different from each other.
	// The UUIDs of the virtual machines to run on hosts different from each other.
	// +listType=set
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

type VSphereComputeClusterVmAntiAffinityRuleParameters struct {

	// The managed object reference
	// ID of the cluster to put the group in.  Forces a new
	// resource if changed.
	// The managed object ID of the cluster.
	// +kubebuilder:validation:Optional
	ComputeClusterID *string `json:"computeClusterId,omitempty" tf:"compute_cluster_id,omitempty"`

	// Enable this rule in the cluster. Default: true.
	// Enable this rule in the cluster.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When this value is true, prevents any virtual
	// machine operations that may violate this rule. Default: false.
	// When true, prevents any virtual machine operations that may violate this rule.
	// +kubebuilder:validation:Optional
	Mandatory *bool `json:"mandatory,omitempty" tf:"mandatory,omitempty"`

	// The name of the rule. This must be unique in the cluster.
	// The unique name of the virtual machine group in the cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUIDs of the virtual machines to run
	// on hosts different from each other.
	// The UUIDs of the virtual machines to run on hosts different from each other.
	// +kubebuilder:validation:Optional
	// +listType=set
	VirtualMachineIds []*string `json:"virtualMachineIds,omitempty" tf:"virtual_machine_ids,omitempty"`
}

// VSphereComputeClusterVmAntiAffinityRuleSpec defines the desired state of VSphereComputeClusterVmAntiAffinityRule
type VSphereComputeClusterVmAntiAffinityRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereComputeClusterVmAntiAffinityRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VSphereComputeClusterVmAntiAffinityRuleInitParameters `json:"initProvider,omitempty"`
}

// VSphereComputeClusterVmAntiAffinityRuleStatus defines the observed state of VSphereComputeClusterVmAntiAffinityRule.
type VSphereComputeClusterVmAntiAffinityRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereComputeClusterVmAntiAffinityRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VSphereComputeClusterVmAntiAffinityRule is the Schema for the VSphereComputeClusterVmAntiAffinityRules API. Provides the VMware vSphere Distributed Resource Scheduler anti-affinity rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereComputeClusterVmAntiAffinityRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.computeClusterId) || (has(self.initProvider) && has(self.initProvider.computeClusterId))",message="spec.forProvider.computeClusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.virtualMachineIds) || (has(self.initProvider) && has(self.initProvider.virtualMachineIds))",message="spec.forProvider.virtualMachineIds is a required parameter"
	Spec   VSphereComputeClusterVmAntiAffinityRuleSpec   `json:"spec"`
	Status VSphereComputeClusterVmAntiAffinityRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereComputeClusterVmAntiAffinityRuleList contains a list of VSphereComputeClusterVmAntiAffinityRules
type VSphereComputeClusterVmAntiAffinityRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereComputeClusterVmAntiAffinityRule `json:"items"`
}

// Repository type metadata.
var (
	VSphereComputeClusterVmAntiAffinityRule_Kind             = "VSphereComputeClusterVmAntiAffinityRule"
	VSphereComputeClusterVmAntiAffinityRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereComputeClusterVmAntiAffinityRule_Kind}.String()
	VSphereComputeClusterVmAntiAffinityRule_KindAPIVersion   = VSphereComputeClusterVmAntiAffinityRule_Kind + "." + CRDGroupVersion.String()
	VSphereComputeClusterVmAntiAffinityRule_GroupVersionKind = CRDGroupVersion.WithKind(VSphereComputeClusterVmAntiAffinityRule_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereComputeClusterVmAntiAffinityRule{}, &VSphereComputeClusterVmAntiAffinityRuleList{})
}
