apiVersion: virtualmachine.terasky.labs/v1alpha1
kind: VSphereVirtualDisk
metadata:
  annotations:
    meta.upbound.io/example-id: virtualmachine/v1alpha1/vspherevirtualdisk
  labels:
    testing.upbound.io/example-name: virtual_disk
  name: virtual-disk
spec:
  forProvider:
    createDirectories: true
    datacenter: ${data.vsphere_datacenter.datacenter.name}
    datastore: ${data.vsphere_datastore.datastore.name}
    size: 40
    type: thin
    vmdkPath: /foo/foo.vmdk
